---
- name: DevOps Challenge Setup
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - nginx
          - git
          - python3
        state: present
        update_cache: yes

    - name: Ensure /var/www/html exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Configure Nginx default webpage
      copy:
        content: "Welcome to the DevOps Challenge"
        dest: /var/www/html/index.html
      notify: Restart nginx

    - name: Start and Enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Setup SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 22'
      notify: Restart SSH

    - name: Create devops user
      user:
        name: devops
        groups: wheel
        append: yes
        shell: /bin/bash

    - name: Ensure .ssh directory exists for devops user
      file:
        path: "/home/devops/.ssh"
        state: directory
        mode: "0700"
        owner: devops
        group: devops

    - name: Generate SSH key for devops user
      openssh_keypair:
        path: "/home/devops/.ssh/id_rsa"
        owner: devops
        group: devops
        mode: 0600
        size: 2048
        type: rsa
        comment: "devops-key"

  handlers:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Restart SSH
      systemd:
        name: sshd
        state: restarted
