---
- name: DevOps Challenge Setup
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - nginx
          - git
          - python3
        state: present
        update_cache: yes

    - name: Ensure /var/www/html exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Configure Nginx default webpage
      copy:
        content: "Welcome to the DevOps Challenge"
        dest: /var/www/html/index.html
      notify: Restart nginx

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Setup SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 22'
      notify: Restart SSH

    - name: Create devops user
      user:
        name: devops
        groups: wheel
        append: yes
        shell: /bin/bash

    - name: Ensure .ssh directory exists for devops user
      file:
        path: "/home/devops/.ssh"
        state: directory
        mode: "0700"
        owner: devops
        group: devops
      become: true

    - name: Generate SSH key for devops user
      openssh_keypair:
        path: "/home/devops/.ssh/id_rsa"  # Path for private key
        owner: devops
        group: devops
        mode: 0600  # Permissions for private key
        size: 2048  # Key size
        type: rsa  # Type of the key (RSA)
        comment: "devops-key"  # Optional comment in the key
      become: true

    - name: Ensure ec2-user has access to the private key
      file:
        path: "/home/devops/.ssh/id_rsa"
        owner: devops
        group: devops
        mode: "0640"  # Readable by the group (ec2-user will need to be in the group)
      become: true

    - name: Add ec2-user to devops group
      user:
        name: ec2-user
        groups: devops
        append: yes
      become: true

    - name: Fetch public key from the generated private key
      command: "cat /home/devops/.ssh/id_rsa.pub"
      register: public_key
      become: true

    - name: Add public key to authorized_keys for devops user
      authorized_key:
        user: devops
        state: present
        key: "{{ public_key.stdout }}"
      become: true
